var root = document.querySelector('#root');
var h1 = document.createElement('h1');
h1.innerText = 'NFT Metadata Generator';
var image = document.createElement('div');
var title = document.createElement('div');
var description = document.createElement('div');
var imageFormWrapper = document.createElement('div');
var imageForm = document.createElement('form');
var imageTextArea = document.createElement('textarea');
var titleFormWrapper = document.createElement('div');
var titleForm = document.createElement('form');
var titleTextArea = document.createElement('textarea');
var descriptionFormWrapper = document.createElement('div');
var descriptionForm = document.createElement('form');
var descriptionTextArea = document.createElement('textarea');
image.innerText = 'ipfs hash:';
title.innerText = 'title:';
description.innerText = 'description:';
imageFormWrapper.className = 'imageFormWrapper';
imageTextArea.className = 'imageTextArea';
titleFormWrapper.className = 'titleFormWrapper';
titleTextArea.className = 'titleTextArea';
descriptionFormWrapper.className = 'descriptionFormWrapper';
descriptionTextArea.className = 'descriptiontextArea';
document.body.appendChild(h1);
document.body.appendChild(description);
document.body.appendChild(descriptionFormWrapper);
descriptionFormWrapper.appendChild(descriptionForm);
descriptionForm.appendChild(descriptionTextArea);
descriptionTextArea.addEventListener("input", function (e) {
    console.log('description: ', descriptionTextArea.value);
});
